version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - .:/app
      - /app/node_modules
