name: Despliegue

on:
  push:
    branches: [ main ]

jobs:
  despliegue:
    runs-on: ubuntu-latest
    needs: calidad
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Construir y subir imagen Docker
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokeweb:latest
        
    - name: Desplegar a producción
      run: |
        echo "Despliegue completado exitosamente"
